version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elastic
    
  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:7.15.2
    environment:
      - output.elasticsearch.hosts=["es01:9200"]
    volumes:  
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elastic
    ports:
      - 8200:8200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: 172.27.10.122
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    networks:
      - elastic
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
